pipeline {
    agent any

    environment {
        NETLIFY_SITE_ID = '523c8a66-4e14-46e5-b961-eb2f5545492b'
        // created at Netlify "Personal access tokens"
        // defined in Jenkins "Credentials"
        NETLIFY_AUTH_TOKEN = credentials('netlify-token')
        // Application version
        // See https://www.jenkins.io/doc/pipeline/tour/environment/ about Jenkins environment variables
        REACT_APP_VERSION = "1.0.$BUILD_ID"
    }

    stages {
        // build custom docker image
        stage('Docker') {
            steps {
                sh 'docker build -t my-playwright .'
            }
        }

        stage('Build') {
            agent {
                docker {
                    image 'node:18-alpine'
                    reuseNode true
                }
            }
            steps {
                sh '''
                    ls -la
                    node --version
                    npm --version
                    npm ci
                    npm run build
                '''
            }
        }

        // Run tests stages in parallel
        stage('Tests') {
            parallel {
                stage('Unit Tests') {
                    agent {
                        docker {
                            image 'node:18-alpine'
                            reuseNode true
                        }
                    }
                    steps {
                        sh '''
                            test -f ./build/index.html
                            npm test
                        '''
                    }
                    post {
                        always {
                            junit 'jest-results/junit.xml'
                        }
                    }
                }

                stage('E2E') { // end 2 end tests using playwright
                    agent {
                        docker {
                            // see https://playwright.dev/docs/docker
                            image 'my-playwright'
                            reuseNode true
                        }
                    }
                    steps {
                        sh '''
                            
                            # image is installed in local hence it needs node_modules...
                            serve -s build &
                            sleep 10
                            npx playwright test --reporter=html
                        '''
                    }
                    post {
                        always {
                            // this script generated by http://localhost:8080/job/learn-jenkins-app/pipeline-syntax/
                            publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, icon: '', keepAll: false, reportDir: 'playwright-report', reportFiles: 'index.html', reportName: 'Playwright Local HTML Report', reportTitles: '', useWrapperFileDirectly: true])
                        }
                    }
                }
            }
        }

        stage('Deploy staging (preprod)') {
            agent {
                docker {
                    // playwright includes node.js so it can be used instead of node image
                    image 'my-playwright'
                    reuseNode true
                }
            }
            steps {
                sh '''
                    # see https://docs.netlify.com/cli/get-started/
                    netlify --version
                    echo "Deploying to staging. Site ID: $NETLIFY_SITE_ID"
                    netlify status
                    # see that when deploying to production, a flag --prod is added,
                    # without it, Netlify will deploy to a temporary random url every time
                    # flag --json added to get deployment info in json format and send it to a file in the workspace
                    netlify deploy --dir=build --json > deploy-output.json
                '''
                script {
                    // parse json file with node-jq and read deployment url,
                    // then set an environment variable so it can be read at next stage
                    env.STAGING_URL = sh(script: "node-jq -r '.deploy_url' deploy-output.json", returnStdout: true)
                }
            }
        }

        stage('Staging (preprod) E2E') { // end 2 end tests against preproduction using playwright
            agent {
                docker {
                    // see https://playwright.dev/docs/docker
                    image 'my-playwright'
                    reuseNode true
                }
            }
            environment {
                // see playwright.config.js
                // get value set in previous stage
                CI_ENVIRONMENT_URL = "${env.STAGING_URL}"
            }
            steps {
                sh '''
                    npx playwright test --reporter=html
                '''
            }
            post {
                always {
                    // this script generated by http://localhost:8080/job/learn-jenkins-app/pipeline-syntax/
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, icon: '', keepAll: false, reportDir: 'playwright-report', reportFiles: 'index.html', reportName: 'Playwright Staging HTML Report', reportTitles: '', useWrapperFileDirectly: true])
                }
            }
        }

        // Continous Delivery: release to prod needs to be approved (hence approval button makes sense)
        // Continues Deployment: doesn´t need approval (no need of an approval button)
        stage('Approval') {
            steps {
                timeout(time: 15, unit: 'MINUTES') {
                    input message: 'Do you wish to deploy to production?',
                        ok: 'Yes, I´m sure I want to deploy'
                }
            }
        }

        stage('Deploy prod') {
            agent {
                docker {
                    image 'my-playwright'
                    reuseNode true
                }
            }
            steps {
                sh '''
                    # see https://docs.netlify.com/cli/get-started/
                    netlify --version
                    echo "Deploying to production. Site ID: $NETLIFY_SITE_ID"
                    netlify status
                    netlify deploy --dir=build --prod
                '''
            }
        }

        stage('Prod E2E') { // end 2 end tests against production using playwright
            agent {
                docker {
                    // see https://playwright.dev/docs/docker
                    image 'my-playwright'
                    reuseNode true
                }
            }
            environment {
                // see playwright.config.js
                CI_ENVIRONMENT_URL = 'https://friendly-conkies-d40ea6.netlify.app'
            }
            steps {
                sh '''
                    npx playwright test --reporter=html
                '''
            }
            post {
                always {
                    // this script generated by http://localhost:8080/job/learn-jenkins-app/pipeline-syntax/
                    publishHTML([allowMissing: false, alwaysLinkToLastBuild: false, icon: '', keepAll: false, reportDir: 'playwright-report', reportFiles: 'index.html', reportName: 'Playwright HTML Report', reportTitles: '', useWrapperFileDirectly: true])
                }
            }
        }
    }
}